model_repository: /home/bdi/Mammo_FDA/TensorRT/LatexOCR/triton/tutorials/Conceptual_Guide/LatexOCR_Triton/model_repository
profile_models:
  - pipeline
bls_composing_models: 
  - encoder
  - decoder
triton_launch_mode: docker
triton_docker_shm_size: 256G
output_model_repository_path: /home/bdi/Mammo_FDA/TensorRT/LatexOCR/triton/tutorials/Conceptual_Guide/LatexOCR_Triton/model_repository/output_dir
export_path: profile_results
override_output_model_repository: true